blog/urls.py
from django.urls import path, include
from blog.views import PostListView, PostDetailView, PostDeleteView, PostUpdateView, PostCreateView


app_name = 'blog'

urlpatterns = [
    # path("", blog_view, name="home"),
    # path('<int:pid>', blog_single, name="single"),
    path("post/", PostListView.as_view(), name="home"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="single"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="update"),
    path("post/create/", PostCreateView.as_view(), name="create"),
    path("api/v1/", include("blog.api.v1.urls")),
]

freelancing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
# from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    # "blog" : BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path("users/", include("users.urls")),
    path('captcha/', include('captcha.urls')),
    path("blog/", include("blog.urls")),
      path("sitemap.xml", sitemap,{"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *


app_name = "users"


urlpatterns = [
    path("login/", login_view, name="login"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("profile/", ProfileView.as_view(), name="profile")
]

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path("", home_view, name="home"),
    path("contact/", contact_view, name="contact"),
]

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link id="theme" rel="stylesheet" href="{% static 'assets/css/blog.css' %}">
    <!-- <link id="theme" rel="stylesheet" href="{% static 'assets/css/blog.darkmode.css' %}"> -->
    <link rel="stylesheet" href="{% static 'assets/css/blogresponsive.css' %}">
    <script src="https://kit.fontawesome.com/006cb90729.js" crossorigin="anonymous"></script>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>Blog</title>
</head>


<body>
    <div class="navigationbar" id="nav">
        <ul>
            <div class="navleft resp">
                <li class="home"><a href="{% url 'website:home' %}"><i class="fa-solid fa-house"></i> home </a></li>
                <li><a href=""><i class="fa-solid fa-handshake"></i> cooperation request</a></li>
                <li><a href="{% url 'blog:home' %}"><i class="fa-solid fa-cubes"></i> blog</a></li>

            </div>
            <div class="navright">
                <li id="theme">
                    <div class="themebutton">
                        <div class="backgroundbutton">

                            <div>
                                <i class="fa-solid fa-sun"></i>
                            </div>
                            <div class="ball" id="ball">
                                <i id="icon" class="fa-solid fa-sun"></i>
                            </div>
                            <div>
                                <i class="fa-solid fa-moon"></i>
                            </div>
                        </div>
                    </div>
                </li>

                <li>
                    <span id="search" class="material-symbols-outlined">search</span>
                    <input type="text" placeholder="search">
                </li>
                <li class="user" id="user">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'users:profile' %}"><img id="img" src="{{ user.profile.image.url }}"
                            alt="{{ user.profile.image }}"></a>
                    <a href="{% url 'users:logout' %}"><button>Logout</button></a>
                    {% else %}
                    <img id="img" src="{{user.image.url}}" alt="">
                    <a href="{% url 'users:login' %}"><button>LogIn</button></a>
                    {% endif %}
                </li>
                <li id="menubutton"><span id="menu" class="material-symbols-outlined">menu</span></li>
            </div>
        </ul>

    </div>
    <div class="responsivenavigationbar" id="sidenavbar">
        <ul>
            <li class="user" id="responsiveuser">
                {% if request.user.is_authenticated %}
                <a href="{% url 'users:profile' %}"><img id="img" src="{{ user.profile.image.url }}"
                        alt="user.profile.image"></a>
                <a href="{% url 'users:logout' %}"><button>Logout</button></a>
                {% else %}
                <img id="img" src="" alt="">
                <a href="{% url 'users:login' %}"><button>Login</button></a>
                {% endif %}
            </li>
            <li class="links home"><a href="{% url 'website:home' %}"><i class="fa-solid fa-house"></i> home </a></li>
            <li class="links"><a href="{% url 'blog:home' %}"><i class="fa-solid fa-cubes"></i> blog</a></li>
            <li class="links"><a href="{% url 'website:home' %}"><i class="fa-solid fa-handshake"></i> cooperation
                    request</a></li>
        </ul>
    </div>
    <li id="menubutton"><span id="menu" class="material-symbols-outlined">menu</span></li>
    </div>
    </ul>
    </div>


    {% block content %}


    {% endblock %}


    <script src="{% static 'assets/js/blog.js' %}"></script>
    </div>