blog/urls.py
from django.urls import path, include
from blog.views import PostListView, PostDetailView, PostDeleteView, PostUpdateView, PostCreateView


app_name = 'blog'

urlpatterns = [
    # path("", blog_view, name="home"),
    # path('<int:pid>', blog_single, name="single"),
    path("post/", PostListView.as_view(), name="home"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="single"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="update"),
    path("post/create/", PostCreateView.as_view(), name="create"),
    path("api/v1/", include("blog.api.v1.urls")),
]

freelancing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
# from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    # "blog" : BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path("users/", include("users.urls")),
    path('captcha/', include('captcha.urls')),
    path("blog/", include("blog.urls")),
      path("sitemap.xml", sitemap,{"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *


app_name = "users"


urlpatterns = [
    path("login/", login_view, name="login"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("profile/", ProfileView.as_view(), name="profile")
]

users/models.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
# Create your models here.


class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_("THE Email must be provided."))
        email = self.normalize_email(email=email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("superuser must have is_superuser=True"))
        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("superuser must have is_staff=True"))

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, null=True)
    last_name = models.CharField(max_length=255, null=True)
    phone_number = models.CharField(max_length=50, null=True)
    image = models.ImageField(upload_to="profiles",
                              default="profiles/black-cloud.png")
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.email}'


class Ticket(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255, null=True)
    description = models.TextField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


@receiver(post_save, sender=CustomUser)
def save_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from users.models import CustomUser
from django import forms


class RegistrationForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30)
    # last_name = forms.CharField(max_length=30)
    # email = forms.EmailField(max_length=35)

    class Meta:
        model = CustomUser
        fields = ['email', 'password1', 'password2']

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render, redirect
from django.views.generic import ListView
from users.forms import RegistrationForm
from django.contrib import messages
from users.models import Profile
from typing import Any, Dict
from django import http
# Create your views here.


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            print("post")
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(request, username=username, password=password)
            if user != None:
                print("User found")
                login(request, user)
                messages.add_message(
                    request, messages.SUCCESS, "Authentication successful, Logged in successfully")
                context = {"user": user}
                return render(request, "users/profile.html", context)
            else:
                messages.add_message(
                    request, messages.ERROR, "Authentication failed")

        form = AuthenticationForm()
        context = {"form": form}
        return render(request, "Users/login.html", context)
    else:
        return redirect('/')


def signup_view(request):
    if not request.user.is_authenticated:
        print("not authenticated")
        if request.method == "POST":
            print("POST")
            form = RegistrationForm(request.POST)
            if form.is_valid():
                print("valid form")
                form.save()
                messages.add_message(
                    request, messages.SUCCESS, "Signed Up successfully !")
                return HttpResponseRedirect("/users/login/")
            else:
                print("invalid form")
                messages.add_message(
                    request, messages.ERROR, "Account did not registered !!!")
        form = RegistrationForm()
        context = {"form": form}
        return render(request, "Users/signup.html", context)
    else:
        return redirect('/')


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(request, messages.SUCCESS,
                             "Successfully logged out")
    else:
        messages.add_message(request, messages.ERROR, "Logging out failed")
    return redirect("/")


class ProfileView(ListView, LoginRequiredMixin):

    model = Profile
    context_object_name = "profile"
    template_name = "Users/profile.html"

    def dispatch(self, request, *args, **kwargs):
        """ IF NOT AUTHENTICATED TO SEE THE PROFILE REDIRECTS TO THE LOGIN PAGE """
        if not request.user.is_authenticated:
            return HttpResponseRedirect("/users/login")
        return super().dispatch(request, *args, **kwargs)

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     context_data["profile"] = Profile.objects.filter(
    #         user=self.request.user)
    #     return context_data

templates/Users/login.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'assets/css/login.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/loginresponsive.css' %}">
    <script src="https://kit.fontawesome.com/006cb90729.js" crossorigin="anonymous"></script>
    <title>LogIn</title>
</head>

<body>
    <div class="container tilt-in-br">
        <div class="left">
            <h1 class="tracking-in-expand">Welcome Back</h1>
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}

                <p
                    style="width: 70%; margin-top: 10px; font-size: 15px; font-family: sans-serif; color: rgba(57, 54, 54, 0.646);">
                    You can also login with:</p>
                <div class="socialmedia">
                    <a href=""><i id="google" class="fa-brands fa-google"></i></a>
                    <a href=""><i id="facebook" class="fa-brands fa-facebook"></i></a>
                    <a href=""><i id="twitter" class="fa-brands fa-twitter"></i></a>
                </div>

                <label for="email">Email:</label>
                <input type="email" name="username" required>

                <label for="password">Password:</label>
                <input type="password" name="password" required>
                <p
                    style="width: 70%;margin-top: 10px; font-size: 13px; font-family: sans-serif; color:rgba(54, 51, 51, 0.817)">
                    <a href="{% url 'users:signup' %}"> you don't have an account ?</a>
                </p>
                <button type="submit">LogIn</button>

            </form>
        </div>
        <div class="right">
            <div class="box">
                <h1>LOGIN</h1>
                <p>If you have trouble of any kind be in touch with admins through opening <a href="#">Tickets...</a>
                </p>
                <p>Don't forget to check the daily Posts and send us back your valuable opinions</p>
            </div>
        </div>
    </div>

</body>

</html>

templates/Users/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>

<body>
    {% if profile.user.first_name == None %}
    <h1>{{ user.profile.first_name }} {{user.profile.last_name}}'s Profile</h1>
    <h3>PhoneNumber: {{ user.profile.phone_number}}</h3>
    {{profile.last_name}}
    {% endif %}
    <h1>{{ user.email }}</h1>
    <img src="{{ user.profile.image.url }}" />
    <a href="{% url 'blog:create' %}">Create post</a>
</body>

</html>

templates/Users/signup.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'assets/css/signin.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/signinresonsive.css' %}">
    <title>SignUp</title>
</head>

<body>
    <div class="container tilt-in-tl">
        <div class="left">
            <h1 class="tracking-in-expand">Registration</h1>
            <form action="{% url 'users:signup' %}" method="post">
                {% csrf_token %}
                <!-- <label for="username">Username:</label>
                <input type="text" name="username"> -->

                <!-- <label for="fname">First name:</label>
                <input type="text"  name="first_name" required>

                <label for="lname">Last name:</label>
                <input type="text" name="last_name" required> -->

                <label for="email">Email:</label>
                <input type="email" name="email" required>

                <label for="pass">Password:</label>
                <input type="password" name="password1" required>

                <label for="password">Password Confirmation:</label>
                <input type="password" name="password2" required>

                <p
                    style="width: 70%;margin-top: 10px; font-size: 13px; font-family: sans-serif; color:rgba(54, 51, 51, 0.817)">
                    <a href="{% url 'users:login' %}">You have an account ?</a>
                </p>

                <button>SignUp</button>
            </form>
        </div>
        <div class="right">
            <div class="box">
                <h1>Advantages :</h1>
                <p>By Registering You Get access to daily posts about programming tips and practical uses in many
                    different languages and their frameworks</p>
                <p>Python's most useful libraries and frameworks such as Django</p>
                <p>JavaScript, C#, C++, and many other programming languages</p>
            </div>
        </div>
    </div>

</body>

</html>